### ISSUE TITLE
AKPickerView not loading from delegate

### ISSUE THREAD

**Issue by kajensen** [Akkyie/AKPickerView#31]
Ok, so I just realized that the 2.0 that I upgraded to last week was just returning an empty AKPickerView (I had a pretty simple implementation via storyboards). I've downgraded to 1.3 and its working fine again. Just curious if this issue has been fixed (I'm not sure exactly what the error even is) in 2.1 or 2.2?

**Comment by Akkyie** [comment]
Just to confirm, did you set `dataSource` properly? From 2.0, data loading has been separated from `delegete`.

**Comment by Akkyie** [comment]
Oh I'm sorry but now I checked and found that I didn't wrote about dataSource in README...

**Comment by kajensen** [comment]
Thanks! yeah, that would be it. I didn't didn't know it had changed.

**Comment by Akkyie** [comment]
Sorry to confuse you. I'm editing it. Thanks for your contribution!
