### ISSUE TITLE
Saving selection when reloading view.

### ISSUE THREAD

**Issue by ChrisOSX** [Akkyie/AKPickerView#32]
Awesome project for starters.

I have this embedded in a table view cell. Everything is implemented, however, I'm stuck on  how the selection gets saved.

More insight on my project:
I have a left table view with multiple selections. One of which is a settings view. The settings view is a table view. In one of the cells is this project. I'm using this to give the user a selection of animations they want to use throughout the app. Zoom Out, Drop In, or the default Push navigation controller.

In the cellForRowAtIndexPath:

                    //Animation Picker
                    self.pickerView = [[AKPickerView alloc] initWithFrame:cell.bounds];
                    self.pickerView.delegate = self;
                    self.pickerView.dataSource = self;
                    self.pickerView.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
                    [cell addSubview:self.pickerView];
                    
                    self.pickerView.font = [UIFont fontWithName:@"HelveticaNeue-Light" size:20];
                    self.pickerView.highlightedFont = [UIFont fontWithName:@"HelveticaNeue" size:20];
                    self.pickerView.interitemSpacing = 25.0;
                    self.pickerView.fisheyeFactor = 0.0002;
                    self.pickerView.pickerViewStyle = AKPickerViewStyle3D;
                    
                    zoom = @"Zoom Out";
                    drop = @"Drop In";
                    push = @"Push";
                    
                    self.titles = @[zoom, drop, push];

                    [self.pickerView reloadData];

Then those get called in your didSelectItem below:

//Selection
pickerView:(AKPickerView *)pickerView didSelectItem:(NSInteger)item {
    if ([self.titles isEqual:zoom]) {
    }
    else if ([self.titles isEqual:drop]) {
    }
    else if ([self.titles isEqual:push]) {
    }
    NSLog(@"%@", self.titles[item]);
}

Each one of those I plan on putting in some NSUserDefaults, so they correspond to the correct animation chosen.

The issue at hand is when leaving then returning to the settings view, it gets reset to the first item.

I've never used something like this before and I feel it's something simple I'm missing, any insight or help would be appreciated.

**Comment by Akkyie** [comment]
Thank you for using my control.

How about calling `[self.pickerView selectItem:animated:]` in  `viewDidAppear` or something?
Your code would be something like this:
``` objc
// In YOURViewController.m
NSString * const YOURAnimationTypeKey = @"YOURAnimationTypeKey";

@implementation YOURViewController

// ...

- (void)viewWillAppear:(BOOL)animated {
	[self.pickerView selectItem:[[NSUserDefaults standardUserDefaults] integerForKey:YOURAnimationTypeKey] animated:false];
}

// ...

- (void)pickerView:(AKPickerView *)pickerView didSelectItem:(NSInteger)item
{
	[[NSUserDefaults standardUserDefaults] setInteger:item forKey:YOURAnimationTypeKey];
}

// ...

@end

```

I hope it helps you.

**Comment by ChrisOSX** [comment]
Most definitely did help, and got me on the right track I believe.

What I had to do was move this to the viewDidLoad:
    //Picker Titles
    zoom = @"Zoom Out";
    drop = @"Drop In";
    push = @"Push";
    self.titles = @[zoom, drop, push]; 

cellForRowAtIndexPath:
[self.pickerView selectItem:[[NSUserDefaults standardUserDefaults] integerForKey:kAnimationTypeKey] animated:false];

and (AKPickerView *)pickerView didSelectItem:
[[NSUserDefaults standardUserDefaults] setInteger:item forKey:kAnimationTypeKey];

This got me to to reload the view and keep the selected item...so far :)

**Comment by Akkyie** [comment]
I'm grad to here that. Nice development!
