### ISSUE TITLE
How to initialize a value for AKPickerView

### ISSUE THREAD

**Issue by thuai** [Akkyie/AKPickerView#35]
I have numbers from 50 to 200.
I want to auto scroll to 100 when PickerView can be seen.

I used to  [self.pickerView scrollToItem:100 animated:NO]  after [self.pickerView reloadData]
But it can't working.

Is there a way to solve this problem?
Thank you!

**Comment by thuai** [comment]
I have solved this problem use selectItem:animated:

**Comment by Akkyie** [comment]
I'm glad to hear that. I close this issue.
