### ISSUE TITLE
DidSelect 

### ISSUE THREAD

**Issue by leo-martin** [Akkyie/AKPickerView#36]
Hello,

I'm using AKPicker view in my app, and the didselect method gets called 4 times when my view appears, I have created a method to init the picker view where I set all its properties, then I added `reloadata` and added it to my view.

My problem is that I want to scroll a page view controller (views inside are collection view) depending on which item is selected in the pickerView, but it gets called too many times on appearance, thus creating a loop in my app.

can you help?

thanks

**Comment by Akkyie** [comment]
Getting delegate method multiple times, something might be wrong with initialisation. Are you using Storyboard or not?
I think I might be able to help you with your code if you don't mind.

**Comment by leo-martin** [comment]
Hello!

thanks for taking the time to answer so quick ok so I have a UIViewController, setup in storyboard and I add programmatically my pickerView

sorry im not really good with markdown yet ^^

here is the code where i add it : 
    [self initPickerView];
    [self.pickerContainerView addSubview:self.pickerView];
    [self.pickerView reloadData];

initPickerView:
    self.pickerView = [[AKPickerView alloc] initWithFrame:CGRectMake(0, 0, self.view.bounds.size.width, 60)]; 
    self.pickerView.delegate = self;
    self.pickerView.dataSource = self;
    self.pickerView.highlightedFont =  [UIFont fontWithName:@"SourceSansPro-Regular" size:17];
    self.pickerView.font = [UIFont fontWithName:@"SourceSansPro-Regular" size:17];
    self.pickerView.highlightedTextColor = [UIColor whiteColor];
    self.pickerView.textColor = [UIColor whiteColor];
    self.pickerView.interitemSpacing = 75;
    self.pickerView.fisheyeFactor = 0.0001;

datasource of akpickerview

- (NSUInteger)numberOfItemsInPickerView:(AKPickerView *)pickerView {
    return [pickerItems count];
}

- (NSString *)pickerView:(AKPickerView *)pickerView titleForItem:(NSInteger)item {
    return pickerItems[item];
}


- (void)pickerView:(AKPickerView *)pickerView didSelectItem:(NSInteger)item {

    
}

Under this picker view, i have a page controller container view where i add multiple collection views, that change when the picker changes, I managed to switch the picker items when i swipe forth and back on my page controller, but i cant do the opposite, switch my collections when i swipe on the picker

**Comment by Akkyie** [comment]
Thank you! iIitialisation looks like normal.

Well then, where did you added this? :
```objc
[self initPickerView];
[self.pickerContainerView addSubview:self.pickerView];
[self.pickerView reloadData];
```
Did you make sure this section is not called multiple times?

(P.S. enclosing your code with  \`\`\` (three backticks) makes it pretty :) )

**Comment by leo-martin** [comment]
this is in my viewDidLoad method, which is not called multiple times ^^

**Comment by Akkyie** [comment]
Could you check whether other delegate/dataSource methods such as numberOfItemsInPickerView are also called multiple times?

**Comment by leo-martin** [comment]
Hello Akkie,

I've just checked and the datasource methods are getting called a lot of times. 

I also noticed that my viewdidload method is getting called, twice, but I don't think it matters here. I use multiple storyboards on my app, (one for login/signup, and the other one for the rest of the app), and I instatiate my login storyboard only if user is not logged in, hence the double load of my home view controller.

The other delegates method such as numberOfItemsInPickerView are called at least 4 times on load.


If you need me to add other bits of my code tell me.

**Comment by Akkyie** [comment]
I'm wondering about, tho you think it doesn't matter, if viewDidLoad called twice in same viewController scene, I think 'addSubview:self.pickerView' also might be called twice. Multiple picker view are on your view perhaps?

**Comment by leo-martin** [comment]
Hello Akkyie,

sorry for the late answer, as of now everything seems to be working fine. I managed to make it work, I have not checked if it still enters delegate methods multiple times.

You can close this issue for now, don't worry I will create an issue if I'm having problems again!

thanks for your help

**Comment by Akkyie** [comment]
I'm sorry I couldn't help you. Feel free to ask me anytime.
