### ISSUE TITLE
display issue

### ISSUE THREAD

**Issue by leo-martin** [Akkyie/AKPickerView#37]
hey I also have a display issue for my pickerView (all the code I put in the other issue is the same)

as you can see the first item is correctly positionned, but the other one is lower and I don't understand why

![picker](https://cloud.githubusercontent.com/assets/1032402/5724262/c2d6efdc-9b4a-11e4-8fbf-92f350419d29.png)

**Comment by Akkyie** [comment]
Sorry for my late response, 

How about trying `self.automaticallyAdjustsScrollViewInsets = NO;` in your viewController? Sometimes it solves some problems.

**Comment by leo-martin** [comment]
Hello Akkie!
Don't worry, I know we live in different timezones ^^
This totally worked thanks!! display is back to normal now!

**Comment by Akkyie** [comment]
I'm glad to hear that. I'm also looking into the other problem.
