### ISSUE TITLE
Swift port

### ISSUE THREAD

**Issue by nawar** [Akkyie/AKPickerView#40]
Awesome work! However, would there be any intention on having a swift version of the library?

**Comment by Akkyie** [comment]
Actually there is, however I didn't know if there are any needs. Now I'm porting it into Swift, and perhaps it might be another repository in order to CocoaPods support or suchlike. Thanks.

**Comment by nawar** [comment]
Great to hear that :)

**Comment by Akkyie** [comment]
Here you are! [The Swift version](https://github.com/Akkyie/AKPickerView-Swift) is released.
It's merely the port of original Objective-C version, but perhaps there might be undiscovered bugs. 
I would appreciate if you report issues when you find them.

**Comment by nawar** [comment]
Awesome!! Thanks man :)
