### ISSUE TITLE
bug in highlightedTextColor

### ISSUE THREAD

**Issue by mjasa** [Akkyie/AKPickerView#46]
When repeated pressure on the edge of the view turns writing color within the view to the highlightedTextColor

{

self.viewHeightPicker.delegate = self;
    self.viewHeightPicker.dataSource = self;
    self.viewHeightPicker.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
    self.viewHeightPicker.font = [UIFont fontWithName:@"HelveticaNeue-Light" size:14];
    self.viewHeightPicker.highlightedFont = [UIFont fontWithName:@"HelveticaNeue" size:14];
    self.viewHeightPicker.highlightedTextColor = [UIColor colorWithRed:1 green:0.41 blue:0.18 alpha:1];
    self.viewHeightPicker.textColor = [UIColor darkGrayColor];
    self.viewHeightPicker.interitemSpacing = 20.0;
    self.viewHeightPicker.fisheyeFactor = 0.0005;
    self.viewHeightPicker.pickerViewStyle = AKPickerViewStyle3D;

}

![screen shot 2015-03-16 at 2 28 30 pm](https://cloud.githubusercontent.com/assets/4077339/6666266/592d33c6-cbeb-11e4-87f4-50781d9eac9b.png)

**Comment by Akkyie** [comment]
Indeed I confirmed a problem that the selected item won't come to the center with repeated taps on other items, but couldn't see turning of font colors. Could you elaborate on your usage of AKPickerView?
Reproducing the problem from making a initial project may also help we solve the problem so much.

**Comment by mjasa** [comment]
i but AKPickerView in UICollectionViewCell and When repeated pressure on the edge of the view turns writing color within the view to the highlightedTextColor

**Comment by Akkyie** [comment]
Well, could you give me a little bit more detailed information?

**Comment by Akkyie** [comment]
I'm sorry but there are few information to figure out when and how your problem happens, so I'm closing this issue. But any additional information are welcomed. Thank you.
