### ISSUE TITLE
First item stays selected

### ISSUE THREAD

**Issue by MarkMolina** [Akkyie/AKPickerView#48]
Bug where at init the first item stays selected. (workaround, programmatically setting the the first item after init)

**Comment by Akkyie** [comment]
Sorry for my late response,

AKPickerView doesn't have a state where no item is selected, so the first item on AKPickerView is initially selected. To change the default selected item, as you say, please programmatically set the the first item after init.

I'm still wondering whether this is the answer you want, and any additional questions are welcomed.

**Comment by Akkyie** [comment]
Passing a week, closing.
