### ISSUE TITLE
Swipe at end of list causes animation redraw jankiness (Swift/Obj-C, iOS8.2, iPhone 5/6)

### ISSUE THREAD

**Issue by carloperez** [Akkyie/AKPickerView#49]
Hey there!

This is a great looking plugin!  Can't use though due to a bug I've found.  Wondering if this is known?

Basically take the demo app and run on iPhone 5 or 6 with iOS 8.2.  Swipe to left or right-most item.  Stop.  Attempt to swipe past that last item on the list and the list will redraw and reanimate from its original position.  Attempt to swipe back towards the rest of the list and the same thing will happen.  

Moving the list slowly seems to be okay but it has to be very slow.  

Only happens on end items.

Changing number of items doesn't help.

Only tried with text (not icons).

Am I missing something here?  Would love to use this!

Let me know how I can help if possible!

Best,
C

**Comment by Akkyie** [comment]
Fixed (c76e77d33f3c16a321a95912deb832118f690f90.)
Thank you for using my control and reporting the issue!

**Comment by carloperez** [comment]
Thanks!  Awesome stuff! : )
