### ISSUE TITLE
UICollectionViewFlowLayout cache mismatched frame (iOS9, xCode7)

### ISSUE THREAD

**Issue by mladen-stankovic** [Akkyie/AKPickerView#62]
AKPickerView outputs this when running on iOS9, xCode7:

Logging only once for UICollectionViewFlowLayout cache mismatched frame
UICollectionViewFlowLayout has cached frame mismatch for index path <NSIndexPath: 0xc000000000000016> {length = 2, path = 0 - 0} - cached value: {{170.66667847961008, 0}, {72.999976338098122, 736}}; expected value: {{170.66666666666666, 0}, {73, 736}}
This is likely occurring because the flow layout subclass AKCollectionViewLayout is modifying attributes returned by UICollectionViewFlowLayout without copying them

**Comment by Ku6ep** [comment]
Why this fix not included to main branch yet?
