### ISSUE TITLE
How can I customise the title in order to have a two line label title? 

### ISSUE THREAD

**Issue by nascimentorafael** [Akkyie/AKPickerView#70]
Hi, 
I've been checking your framework out to use it in a project of mine.
I would like to build something similar to this print: 
![image](https://cloud.githubusercontent.com/assets/5751411/12626706/c6c294ae-c518-11e5-8d90-bcb22d81df92.png)
I was wondering if there is a way to customise the label or the picker view itself in order to have a two line title. It would be a title and a subtitle.
Thank you for the attention.

**Comment by mrhaxic** [comment]
@nascimentorafael I thought you can do it by using `UIScrollView` and enable pagination
